# Generated by Django 6.0.6 on 2026-07-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_placed', 'Order placed'), ('order_paid', 'Order paid'), ('order_status', 'Order status changed'), ('order_received', 'Order confirmed received by customer'), ('low_stock', 'Low stock alert'), ('return_requested', 'Return requested'), ('return_approved', 'Return approved'), ('return_rejected', 'Return rejected'), ('return_refunded', 'Return refunded')], max_length=24),
        ),
    ]
