# Generated by Django 6.0.6 on 2026-06-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('results', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-cached_at',),
            },
        ),
    ]
