# Generated by Django 5.1.4 on 2026-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL identifier; auto-generated from title if left blank.', max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, help_text='One-sentence elevator pitch shown above the body.', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Policy body. Blank lines become paragraph breaks; the page renders each block separately.')),
                ('return_window_days', models.PositiveSmallIntegerField(default=14, help_text='How many days from delivery customers can open a return.')),
                ('requires_receipt', models.BooleanField(default=True, help_text='If true, customers must include a receipt or order number.')),
                ('restocking_fee_percent', models.PositiveSmallIntegerField(default=0, help_text='Percent of the order value retained as a restocking fee.')),
                ('is_active', models.BooleanField(default=True, help_text='When off, the policy is hidden from the customer endpoint but still appears in the admin list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
                'indexes': [models.Index(fields=['is_active', '-updated_at'], name='policies_re_is_acti_821bd6_idx')],
            },
        ),
    ]
