# Generated by Django 6.0.6 on 2026-07-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_received_at_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=16)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Executed', 'Executed'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Initiated', max_length=16)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('redirect_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_37df30_idx')],
            },
        ),
    ]
