# Generated by Django 5.1.4 on 2026-07-05 00:31
"""Backfill snapshot fields on existing PaymentAttempt rows.

Existing rows were created under the previous flow where every attempt
had a non-null ``Order``. With the new deferred-Order flow each attempt
must carry the order's data itself (user, amount, items, address,
payment_method, and a unique ``draft_number`` placeholder) so the
execute step can materialize the Order once payment confirms.

After this migration, ``user`` is made NOT NULL and ``draft_number`` is
made UNIQUE — every attempt must own these going forward.
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_snapshot(apps, schema_editor):
    PaymentAttempt = apps.get_model("payments", "PaymentAttempt")
    for attempt in (
        PaymentAttempt.objects.select_related("order", "order__user").iterator()
    ):
        order = attempt.order
        if order is None:
            continue
        attempt.user_id = order.user_id
        attempt.draft_number = f"MH-D{attempt.pk:06d}"
        attempt.amount = order.total_amount
        addr = order.shipping_address or {}
        attempt.payment_method = (addr.get("payment_method") or "").lower()
        attempt.items = order.items or []
        attempt.shipping_address = addr
        attempt.save(
            update_fields=[
                "user",
                "draft_number",
                "amount",
                "payment_method",
                "items",
                "shipping_address",
            ]
        )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_received_at_alter_order_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='draft_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='shipping_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_238565_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_681c90_idx'),
        ),
        # Backfill existing rows from their (already-populated) Order.
        migrations.RunPython(_backfill_snapshot, _noop_reverse),
        # Tighten user to NOT NULL — every new attempt must own a user.
        migrations.AlterField(
            model_name='paymentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        # Add unique constraint on draft_number now that every row has one.
        migrations.AlterField(
            model_name='paymentattempt',
            name='draft_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
