# Generated by Django 5.1.4 on 2026-07-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentattempt_amount_paymentattempt_draft_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
