# Generated by Django 6.0.6 on 2026-06-25 10:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='camera_mp',
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='announced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='expert_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='made_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='market_status',
            field=models.CharField(choices=[('available', 'Available'), ('upcoming', 'Upcoming'), ('rumored', 'Rumored'), ('discontinued', 'Discontinued')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='always_on_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='architecture',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='productspec',
            name='audio_features',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='audio_jack',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='battery_placement',
            field=models.CharField(blank=True, default='Non-removable', max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='battery_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='bezel_less',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productspec',
            name='brightness_peak_nits',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='productspec',
            name='brightness_typical_nits',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='productspec',
            name='build_material',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_aperture',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_autofocus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_eis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_flash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_focal_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_image_resolution',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_ois',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_resolution_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_resolution_mp',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_sensor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_sensor_size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_settings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_setup',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_shooting_modes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_video_fps',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_video_resolution',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='camera_zoom',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='chipset',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productspec',
            name='cpu_cores',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='productspec',
            name='cpu_details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='display_cm',
            field=models.DecimalField(decimal_places=2, default=16.51, max_digits=5),
        ),
        migrations.AddField(
            model_name='productspec',
            name='display_type',
            field=models.CharField(blank=True, choices=[('amoled', 'AMOLED'), ('ltps_amoled', 'LTPS AMOLED'), ('ltpo_amoled', 'LTPO AMOLED'), ('oled', 'OLED'), ('ips_lcd', 'IPS LCD'), ('tft', 'TFT'), ('pls_lcd', 'PLS LCD')], default='amoled', max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='edge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='fabrication_nm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='face_unlock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='fingerprint_position',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='fingerprint_sensor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='fingerprint_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='form_factor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='front_camera_aperture',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productspec',
            name='front_camera_autofocus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='front_camera_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='front_camera_flash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='front_camera_setup',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='front_camera_video_resolution',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='gprs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='gps',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='gpu',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='has_2g',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='has_3g',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='has_4g',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='hdr_support',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='infrared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='ip_rating',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='loudspeaker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='network_bands',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='network_speed',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productspec',
            name='nfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspec',
            name='notch_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='os_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='pixel_density_ppi',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='productspec',
            name='quick_charging',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='ram_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='refresh_rate_secondary_hz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='resolution_height',
            field=models.PositiveSmallIntegerField(default=2400),
        ),
        migrations.AddField(
            model_name='productspec',
            name='resolution_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productspec',
            name='resolution_width',
            field=models.PositiveSmallIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='productspec',
            name='ruggedness',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='screen_protection',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='screen_to_body_ratio_pct',
            field=models.DecimalField(decimal_places=2, default=85.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productspec',
            name='sensors_list',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='productspec',
            name='sim_size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='sim_slot',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productspec',
            name='storage_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='touch_screen',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productspec',
            name='usb_otg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='usb_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productspec',
            name='video_formats',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='volte',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='waterproof',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productspec',
            name='weight_g',
            field=models.PositiveSmallIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='productspec',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='wifi_hotspot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='wireless_charging',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productspec',
            name='wlan',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='battery_mah',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='charging_watts',
            field=models.PositiveSmallIntegerField(default=67),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='display_inches',
            field=models.DecimalField(decimal_places=2, default=6.5, max_digits=5),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('display_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('performance_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('camera_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('battery_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('software_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('connectivity_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('value_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('verdict', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_breakdown', to='products.product')),
            ],
        ),
    ]
