# Generated by Django 5.1.4 on 2026-06-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productspec_camera_mp_brand_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='Premium Tech Core · 2024 Lineup', max_length=80)),
                ('title', models.CharField(blank=True, default='The phone you actually want.', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='Premium smartphones', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
            ],
            options={
                'verbose_name': 'Hero feature',
                'verbose_name_plural': 'Hero feature',
            },
        ),
    ]
